openmrs/openmrs-contrib-atlas

- public/js/atlas.js
This should fix this issue, and related bugs I can found.
For instance, duplicate edit, trash or undo icon inside the bubble.
> ATLAS-117: Duplicate "This is not me." buttons.

- app/views/index.blade.php
- public/js/distribution.js
- public/js/user.js
bug fixes for disappearing distro, distro name shortening, and filter for standard distro added
> Latest code with bug fixes

- app/controllers/AuthController.php
> Minor fix: typo

- README.md
Adds link to atlas 3.0 module in readme.md
> Added link to atlas 3.0 module in readme.md

- .dockerignore
- Dockerfile
- db.js
- docker-compose.yml
- routes/distributions.js
- script.sh
> Adds dockerfile

- routes/markerSites.js
Added marker delete route which is present in master branch but not in 3.x .
> Added marker delete route

- routes/index.js
- routes/types.js
- routes/versions.js
Wrote GET API to retrieve lists of types and versions.
> ATLAS-140: Write API to get all types and version

- db/bootstrap.v3.sql
Created tables for types and versions using bootstrap.sql .
> ATLAS-139: Edit bootstrap.sql with types and versions database schema

- public/js/atlas.js
- public/js/type.js
- public/js/user.js
- public/js/version.js
- views/index.ejs
Wrote code to retrieve types and versions into the client side, and used them where applicable.
JIRA Issue: https://issues.openmrs.org/browse/ATLAS-141?jql=project%20%3D%20ATLAS
> ATLAS-141: Replace hardcode to use types and versions API

- db/bootstrap.v3.sql
JIRA Issue: https://issues.openmrs.org/browse/ATLAS-142?jql=project%20%3D%20ATLAS
> ATLAS-142: Save hardcoded types and versions in the database

- public/js/atlas.js
- public/js/user.js
- routes/markerSites.js
- views/index.ejs
Admins can edit or delete any marker.
> ATLAS-143: Allow admins to manage all markers

- routes/markerSites.js
Since [ATLAS-135](https://issues.openmrs.org/browse/ATLAS-135?jql=project%20%3D%20ATLAS), we have 2 GET '/marker' routes, making the 2nd one (which filters based on types, versions, and distributions) inaccessible.
JIRA issue: https://issues.openmrs.org/browse/ATLAS-144?jql=project%20%3D%20ATLAS
> ATLAS-144: Merge the 2 GET '/markers' routes in markerSites.js

- routes/distributions.js
- routes/markerSites.js
- routes/types.js
- routes/versions.js
- utils.js
Wrote API to manage types, versions, and distributions.
JIRA Issue: https://issues.openmrs.org/browse/ATLAS-145
> ATLAS-145: Write API to manage types, versions, and distributions

- routes/admin.js
- views/admin/partials/header.ejs
- views/admin/types/editType.ejs
- views/admin/types/newType.ejs
- views/admin/types/types.ejs
@bmamlin @harsha89 @cintiadr Here's the interface to manage types. I wrote the backend too, but it hasn't been tested yet, as I felt that it would be easier once #60 gets merged. I created another PR to manage versions. The distributions page still needs some work.
You can find images of the interface in the [JIRA issue](https://issues.openmrs.org/browse/ATLAS-151?jql=project%20%3D%20ATLAS). How do you think it could be improved? :)
> ATLAS-151: Created user interface to manage types

- routes/admin.js
- routes/versions.js
- views/admin/versions/editVersion.ejs
- views/admin/versions/newVersion.ejs
- views/admin/versions/versions.ejs
@bmamlin @harsha89 @cintiadr Here's the interface to manage versions. The backend calls are ready, but haven't been tested yet, as I felt that it would be easier once #60 gets merged. [Here's the PR](https://github.com/openmrs/openmrs-contrib-atlas/pull/61) about types. The distributions one is on the way. :)
You can find images of the interface in the [JIRA issue](https://issues.openmrs.org/browse/ATLAS-152?jql=project%20%3D%20ATLAS). How do you think it could be improved? :)
> ATLAS-152: Created user interface to manage versions

- routes/types.js
- views/admin/types/editType.ejs
- views/admin/types/newType.ejs
- views/admin/types/types.ejs
JIRA issue: https://issues.openmrs.org/browse/ATLAS-156
> ATLAS-156: Fixed admin user interface to manage types

- routes/admin.js
- routes/distributions.js
- views/admin/distributions/distributions.ejs
- views/admin/distributions/editDistribution.ejs
- views/admin/distributions/newDistribution.ejs
@bmamlin @harsha89 @cintiadr Here's the interface to manage distributions. The backend calls are ready, but haven't been tested yet, as I felt that it would be easier once #60 gets merged.
You can find images of the interface in the [JIRA issue](https://issues.openmrs.org/browse/ATLAS-153). How do you think it could be improved? :)
> ATLAS-153: Created user interface to manage distributions

- public/js/atlas.js
- public/js/user.js
- routes/markers.js
OpenMRS version of a marker wasn't getting saved when a marker is getting created or updated.
JIRA issue - https://issues.openmrs.org/browse/ATLAS-160
> ATLAS-160: OpenMRS version of a marker isn't getting saved

- public/js/atlas.js
JIRA issue: https://issues.openmrs.org/browse/ATLAS-162?jql=project%20%3D%20ATLAS
> ATLAS-162: Show fading tip even when fading turned off

- public/js/atlas.js
JIRA issue: https://issues.openmrs.org/browse/ATLAS-163?jql=project%20%3D%20ATLAS
> ATLAS-163: Start fading markers after a year has passed

- public/js/atlas.js
- routes/markers.js
JIRA issue: https://issues.openmrs.org/browse/ATLAS-171?jql=project%20%3D%20ATLAS
> ATLAS-171: Atlas breaks if version of a marker is 'Other' or 'Unknown'

- public/js/user.js
- routes/markers.js
JIRA issue: https://issues.openmrs.org/browse/ATLAS-164?jql=project%20%3D%20ATLAS
> ATLAS-164: Markers can be updated using the update button

- public/js/user.js
- routes/distributions.js
- routes/markers.js
- routes/types.js
- routes/versions.js
- views/admin/distributions/distributions.ejs
- views/admin/distributions/editDistribution.ejs
- views/admin/distributions/newDistribution.ejs
- views/admin/types/editType.ejs
- views/admin/types/newType.ejs
- views/admin/types/types.ejs
- views/admin/versions/editVersion.ejs
- views/admin/versions/newVersion.ejs
- views/admin/versions/versions.ejs
JIRA issue: https://issues.openmrs.org/browse/ATLAS-172?jql=project%20%3D%20ATLAS
> ATLAS-172: Unable to save some markers due to incorrect headers

- public/js/user.js
JIRA issue: https://issues.openmrs.org/browse/ATLAS-165?jql=project%20%3D%20ATLAS
> ATLAS-165: Saving a marker does not update the last updated date until page is reloaded

- public/js/atlas.js
JIRA issue: https://issues.openmrs.org/browse/ATLAS-173?jql=project%20%3D%20ATLAS
> Hiding street view and zoom controls

- public/js/atlas.js
- public/js/user.js
- routes/markers.js
JIRA issue: https://issues.openmrs.org/browse/ATLAS-180
> ATLAS-180: Replace site's uid attribute with the created_by attribute

- public/js/atlas.js
I created a new branch on the repo to test on the staging server, because I didn't have a proper google api key.
JIRA issue: https://issues.openmrs.org/browse/ATLAS-174?jql=project%20%3D%20ATLAS
(Is this what this is supposed to look like? I've no idea :| )
> ATLAS-174: Fixed clustering of markers

- public/js/user.js
- routes/distributions.js
- routes/markers.js
- routes/types.js
- routes/versions.js
JIRA issue: https://issues.openmrs.org/browse/ATLAS-175?jql=project%20%3D%20ATLAS
> ATLAS-175: Make POST, PATCH and DELETE routes return the whole resource

- public/js/user.js
JIRA issue: https://issues.openmrs.org/browse/ATLAS-183
> ATLAS-183: removed confirmation popup when updating marker

- db/atlasversions.sql
- routes/markers.js
JIRA Issue: https://issues.openmrs.org/browse/ATLAS-182
The PR hasn't been tested on Safari, as I don't have it on Ubuntu, but it doesn't seem to break anything on Mozilla/Chrome.
> ATLAS-182: Invalid response on safari when updating marker

- public/js/user.js
JIRA issue: https://issues.openmrs.org/browse/ATLAS-186?jql=project%20%3D%20ATLAS
I think we may need the delete option to clear a marker that hasn't been saved.
> ATLAS-186: Do not show update option for markers that have not been saved

- db/rsstable.sql
- routes/markers.js
- routes/rss.js
- utils.js
JIRA issue: https://issues.openmrs.org/browse/ATLAS-187?jql=project%20%3D%20ATLAS
> ATLAS-187: Add image to RSS feed

- public/js/atlas.js
JIRA issue: https://issues.openmrs.org/browse/ATLAS-188
> ATLAS-188: Marker links in RSS feed must center and zoom in on the marker

- routes/markers.js
JIRA issue: https://issues.openmrs.org/browse/ATLAS-189
> ATLAS-189: Editing marker without selecting an image clears the image

- public/js/atlas.js
JIRA issue: https://issues.openmrs.org/browse/ATLAS-191
> ATLAS-191: Improved OpenMRS Atlas loading speed

- public/js/user.js
- routes/markers.js
JIRA issue: https://issues.openmrs.org/browse/ATLAS-192
It took me a while to find the error but it was being caused when we were passing null values (which we were getting from the database) to [these 3 lines](https://github.com/openmrs/openmrs-contrib-atlas/blob/master/public/js/user.js#L556-L558). Setting these entries to 0 in the database solved the issue.
Dropping a new marker created more of these issues, so I set those attributes to 0 in newSite.
> ATLAS-192: Fixed specified value 'null' is not a valid number errors

- public/js/atlas.js
- public/js/user.js
JIRA issue: https://issues.openmrs.org/browse/ATLAS-193?jql=project%20%3D%20ATLAS
> ATLAS-193: 'Download' button on atlas-stg downloads map image without markers

- db/02_updates.sql
JIRA issue: https://issues.openmrs.org/browse/ATLAS-197
> ATLAS-197: Updated updates.sql to fix legacy usernames in atlas mysql database

- public/js/atlas.js
- public/js/user.js
JIRA issue: https://issues.openmrs.org/browse/ATLAS-198
> ATLAS-198: Turn off fading and show bubble when user is editing their markers

- public/js/atlas.js
JIRA issue: https://issues.openmrs.org/browse/ATLAS-200
> ATLAS-200: View and edit bubbles showing simultaneously

- public/js/atlas.js
- public/js/distribution.js
- public/js/module.js
- public/js/type.js
- public/js/user.js
- public/js/version.js
- routes/api/auth.js
- routes/api/distributions.js
- routes/api/index.js
- routes/api/markers.js
- routes/api/types.js
- routes/api/unsubscribed.js
- routes/api/versions.js
- routes/index.js
- views/admin/admin.ejs
- views/admin/distributions/distributions.ejs
- views/admin/distributions/editDistribution.ejs
- views/admin/distributions/newDistribution.ejs
- views/admin/types/editType.ejs
- views/admin/types/newType.ejs
- views/admin/types/types.ejs
- views/admin/versions/editVersion.ejs
- views/admin/versions/newVersion.ejs
- views/admin/versions/versions.ejs
- views/index.ejs
JIRA issue: https://issues.openmrs.org/browse/ATLAS-196
> ATLAS-196: Distinguish between web and REST endpoints using an api folder

- routes/api/auth.js
- routes/api/markers.js
JIRA issue: https://issues.openmrs.org/browse/ATLAS-205?jql=project%20%3D%20ATLAS
> ATLAS-205: Do not expose data payloads sent from module directly

- public/js/user.js
JIRA issue: https://issues.openmrs.org/browse/ATLAS-204?jql=project%20%3D%20ATLAS
> ATLAS-204: Removed unnecessary dialogs

- routes/default.js
- views/index.ejs
JIRA issue: https://issues.openmrs.org/browse/ATLAS-201
> ATLAS-201: Enabled Google Analytics for OpenMRS Atlas

- app.js
- db.js
- ldap.js
- routes/api/auth.js
- routes/api/distributions.js
- routes/api/markers.js
- routes/api/types.js
- routes/api/unsubscribed.js
- routes/api/versions.js
- routes/authentication.js
- routes/rss.js
- utils.js
JIRA issue: https://issues.openmrs.org/browse/ATLAS-202
I replaced all the server-side console.logs with logger.errors and logger.debugs. The http traffic was being logged by the package 'morgan'. The logs above are morgan in common mode while the ones below are in combined mode. Which one should we use?
> ATLAS-202: Cleaned up server logs

- public/js/user.js
JIRA issue: https://issues.openmrs.org/browse/ATLAS-209
> ATLAS-209: Only show co-owners to users who can edit a marker

- views/index.ejs
JIRA issue: https://issues.openmrs.org/browse/ATLAS-208?jql=project%20%3D%20ATLAS
> ATLAS-208: Search dialog behaves differently when authenticated

- public/js/tools.js
JIRA issue: https://issues.openmrs.org/browse/ATLAS-210
> ATLAS-210: Hide controls when creating download image

- public/js/distribution.js
- public/js/module.js
- public/js/type.js
- public/js/user.js
- public/js/version.js
- routes/api/auth.js
- routes/api/distributions.js
- routes/api/markers.js
- routes/api/report.js
- routes/api/types.js
- routes/api/unsubscribed.js
- routes/api/versions.js
- routes/module.js
- routes/rss.js
- utils.js
- views/admin/distributions/distributions.ejs
- views/admin/distributions/editDistribution.ejs
- views/admin/distributions/newDistribution.ejs
- views/admin/types/editType.ejs
- views/admin/types/newType.ejs
- views/admin/types/types.ejs
- views/admin/versions/editVersion.ejs
- views/admin/versions/newVersion.ejs
- views/admin/versions/versions.ejs
JIRA Issue: https://issues.openmrs.org/browse/ATLAS-203
@bmamlin I created a constants.js file because there 30-40 lines logging database errors! If this is ok, perhaps we could copy in other constants from the codebase in a future PR?
> ATLAS-203: Report server errors to the user

- package-lock.json
- package.json
- public/css/data.css
- routes/api/report.js
- views/data.ejs
JIRA issue: https://issues.openmrs.org/browse/ATLAS-211
Its deployed on [staging](https://atlas-stg.openmrs.org/data).
> ATLAS-211: Added country-level choropleth and modules piechart
