- public/js/atlas.js
There isn't any issue reported for this problem and 
Issue is  : if clustering is enabled by checking the clustering in view dropdown at [atlas.openmrs.org](https://atlas.openmrs.org/), it should show the clustering of pins but that won't show up since the markercluster code is moved to the Github. 
I changed the code locally and it works fine after this fix.
> added the clusterer image

- routes/markerSites.js
Based on [this issue](https://github.com/ShekharReddy4/openmrs-contrib-atlas-node/issues/4). Weirdly, I couldn't test the code I wrote, as the '/login/' route leads to 'http://localhost:8080/authenticate/atlas' which I don't know how to set up. If I can get that url running, I think I could test and confirm whether my code does the job.
> Added authentication check for post routes

- conf.example.js
- ldap.js
- package-lock.json
- package.json
- routes/authentication.js
- views/login.ejs
Added login via LDAP. The user can click on the 'Sign In' button, to reach a (not so shiny)login page.
On entering the correct credentials, the user is logged into the Atlas, and can do Atlas stuff.
Wrong credentials give us an error message (I think I'll focus on the looks of the message in a future PR).
> Added login via LDAP

- public/js/atlas.js
- public/js/user.js
- routes/markerSites.js
- views/index.ejs
Fixed add, delete, and edit markers functionality. [Here's a video](https://www.youtube.com/watch?v=9iKtygoxvjw) of the atlas in its current state.
> Fixed add, delete, and edit markers functionality

- README.md
The 'GOOGLE_MAPS_JS_API_KEY' environment variable is being used to display the map on the atlas. But the docker-compose.yml doesn't contain it, and the README.md doesn't mention it.
> ATLAS-137: Add GOOGLE_MAPS_JS_API_KEY environment variable to README.md and docker of Atlas 3.x

- docker-compose.yml
- public/js/atlas.js
- routes/markerSites.js
- views/index.ejs
Changed `GET /markerSites` to `GET /markers` and replaced `GET /marker/uid/:uid` with `GET /markers?username={username}`.
> ATLAS-135: Change markerSites to markers in the marker API

- app.js
- conf.example.js
- ldap.js
@cintiadr @bmamlin @harsha89 Whether the user is an admin or not is now stored in the user session object.
Here's a sample user session object.
```
{ dn: 'uid=testadmin,ou=users,dc=openmrs,dc=org',
controls: [],
uid: 'testadmin',
cn: 'Admin',
sn: 'User',
displayName: 'Test Admin User',
mail: 'testadminuser@gmail.com',
admin: true }
```
I'm starting to think that maybe a flag wouldn't be the best idea if the user belonged to multiple groups. Maybe its better to ignore that for now, as mentioned my @bmamlin on talk yesterday. What do you think? :)
> ATLAS-134: Check and store whether user is admin on login

- public/js/user.js
- routes/markerSites.js
Updated the update markers route to use PATCH instead of POST.
> ATLAS-136: Add support for PATCH in Atlas server

- routes/markerSites.js
@bmamlin @harsha89 @cintiadr Checking whether the marker belongs to the authenticated user, or whether the user is an admin before executing the create/edit marker SQL.
> ATLAS-150: Add checks in the API before the sql syntax is executed

- public/js/user.js
- routes/markerSites.js
@bmamlin @harsha89 @cintiadr If show counts is off, only creator and admins can view it. Currently counts are being returned but are being hidden by the front end, which isn't the way it should be done. What do you think is a good way to avoid this?
I could think of using an SQL statement likeL
```
SELECT * FROM atlas WHERE show_counts=1
UNION (SELECT <columns except counts> FROM WHERE show_counts=0);
```
Another way I could think of is to write a JS function to filter out counts on the server.
JIRA issue: https://issues.openmrs.org/browse/ATLAS-154
> ATLAS-154: Show hidden counts only to creator and admins

- public/js/user.js
It displays the version correctly at first, but empties and closes automatically on clicking on it.
JIRA issue: https://issues.openmrs.org/browse/ATLAS-158
> ATLAS-158: Fixed versions dropdown in the edit marker bubble

- public/js/user.js
When a new marker is created or an existing is updated, the legend isn't being updated.
JIRA issue: https://issues.openmrs.org/browse/ATLAS-159
> ATLAS-159: Legend isn't being updated until the page is refreshed

- public/js/atlas.js
View --> Distros, marks every marker as 'Other' and colors them purple.
JIRA issue: https://issues.openmrs.org/browse/ATLAS-161
On Atlas staging:
After the fix on my pc:
> ATLAS-161: Viewing markers by distributions marks all markers as 'Other'

- public/css/atlas.css
- public/js/atlas.js
- views/index.ejs
Added a "My Markers" checkbox under "View" to display only the user's markers, as suggested by @cintiadr .
JIRA issue: https://issues.openmrs.org/browse/ATLAS-176?jql=project%20%3D%20ATLAS
> ATLAS-176: Make it easier for a user to spot his own markers

- routes/markers.js
Handle the condition where a marker is not found, returning at 404 Not Found to the client.
> ATLAS-185: Deleting or updating invalid marker crashes server

- app.js
- db/atlas_image_to_blob.sql
- db/bootstrap.sql
- public/css/atlas.css
- public/js/user.js
- routes/markers.js
- routes/rss.js
- views/index.ejs
JIRA issue: https://issues.openmrs.org/browse/ATLAS-178
The images are being stored on the MySQL server as a BLOB.
(I'm still looking for the CSS issue that's causing the image to float to the left, instead having its own row)
> ATLAS-178: Support upload of marker images

- conf.example.js
- db/01_database.sql
- db/02_updates.sql
- package-lock.json
- package.json
- public/js/atlas.js
- public/js/user.js
- routes/authentication.js
- routes/default.js
- routes/index.js
- routes/markers.js
- routes/unsubscribed.js
- utils.js
- views/index.ejs
JIRA issue: https://issues.openmrs.org/projects/ATLAS/issues/ATLAS-168?filter=allissues
--- WORK IN PROGRESS ---
See [this](https://talk.openmrs.org/t/gsoc-2019-openmrs-atlas-3-1/22226/175).
> ATLAS-168: Notify users when their marker is fading

- public/css/atlas.css
JIRA issue: https://issues.openmrs.org/browse/ATLAS-199
Adding the tooltip to the info container disables the tooltip (hovering doesn't display the tooltip).
This is the fastest solution I could think of. :/
> ATLAS-199: Site fade tip text extending beyond bubble

- public/js/atlas.js
- public/js/module.js
- public/js/user.js
- routes/api/auth.js
- routes/api/index.js
- routes/api/markers.js
- routes/api/module.js
- routes/default.js
- routes/index.js
- routes/module.js
- utils.js
- views/index.ejs
JIRA Issue: https://issues.openmrs.org/browse/ATLAS-195
----- WATCH OUT : BUGGY CODE AHEAD -----
I created a module mode for the module to interact with atlas. But I've a few questions regarding the implementation, like,
- What exactly triggers module mode? Is it the POST sent by the module, or the one sent to the iframe by the parent page? Here, its a post doing it. 'module mode' is stored in the session so that the user can mess around in the iframe and still access module mode. This probably needs to be changed though.
- Are the route names ok?
This PR goes together with this PR: https://github.com/openmrs/openmrs-module-atlas/pull/11
TO DO:
-
- Add server-side checks for whether the marker being linked belongs to the user.
> ATLAS-194: Create module mode

- routes/api/index.js
- routes/api/report.js
- routes/module.js
- utils.js
JIRA issue: https://issues.openmrs.org/browse/ATLAS-206
`GET /api/report/foo` returns something like :
```
{
"module": "foo",
"versions": {
"1.0.0": 7,
"1.2": 5,
"2.0": 17
}
}
```
Would be perhaps want a GET to return details of all modules being used?
> ATLAS-206: Added basic reporting resource to API

- public/css/atlas.css
- public/js/atlas.js
- public/js/tools.js
- public/js/user.js
- views/index.ejs
JIRA issue: https://issues.openmrs.org/browse/ATLAS-169
The markers' names are checked to see if they contain the search term as a substring. If no, the sites are hidden. Clicking search displays a clear button which can be clicked to revert the map to normal. Is there anything that you'd like to improve about the PR?
The changes can be tested on [staging](https://atlas-stg.openmrs.org/).
> ATLAS-169: Added search for markers

- README.md
Jira issue: https://issues.openmrs.org/browse/GCI-341
Under "create environment variables in your bash", `DB_USERNAME` and `DB_PASSWORD`'s values have been replaced with `<mysql username>` and `<mysql password>` respectively.
> [GCI-341] Update readme in opennmrs-contrib-atlas
